version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=election_counter
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - election-net

  db:
    image: postgres:15
    container_name: election-db
    environment:
      - POSTGRES_DB=election_counter
      - POSTGRES_USER=laravel_user
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - election-net

networks:
  election-net:
    driver: bridge

volumes:
  postgres_data: